bookmarks/bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    # static 为媒体文件生成正确的url
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
]

bookmarks/images/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.text import slugify
# Create your models here.


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)

    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


    # def get_absolute_url(self):
    #     return reverse('images:detail', args=[self.id, self.slug])

bookmarks/images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in {'jpg', 'jpeg'}:
            raise forms.ValidationError('Error extension')
        return url

    def save(self, commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'

        # download image from the given URL
        res = request.urlopen(image_url)
        # image.image.save() 中的 save() 方法是 Django FieldFile 类的一个方法
        image.image.save(image_name, ContentFile(res.read()), save=False)
        if commit:
            image.save()
        return image

bookmarks/images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import ImageCreateForm
from .models import Image
from common.decorators import ajax_required
from actions.utils import create_action


# Create your views here.
@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'bookmarked image', new_item)
            messages.success(request, 'Image added successfully')
            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm(request.GET)
    return render(request, 'images/image/create.html', {'form': form, 'section': 'images'})


def image_detail(request, *args, **kwargs):
    image = get_object_or_404(Image, id=kwargs['id'], slug=kwargs['slug'])
    return render(request, 'images/image/detail.html', {'section': 'images', 'image': image})


@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        # image.users_like 不是一个列表，而是一个 ManyToMany 关系的管理器。你不能直接对其调用 len() 函数，也不能直接在列表推导式中使用它。你需要调用它的 all()
        # 方法来获取一个包含所有相关对象的查询集，然后你可以在这个查询集上使用 len() 函数或者列表推导式
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
            if image.users_like.count() > 0:
                users_likes = [{'url': user.profile.photo.url, 'first_name': user.first_name} for user in
                               image.users_like.all()]
            else:
                users_likes = []
            return JsonResponse({'status': 'ok', 'users_like': users_likes})
        except Exception as e:
            return JsonResponse({'status': 'error', 'error': str(e)})
    return JsonResponse({'status': 'error'})


@login_required
def image_list(request):
    # todo 开始时没有滚动条的话，就无法拉到窗口底部发起ajax请求获取更多的图片，但是更改窗口大小即可；不知道改怎么修复
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # 在许多使用 AJAX 的无限滚动或分页系统中，当用户滚动到页面底部时，会自动发送一个 AJAX 请求以获取更多的内容。这个 AJAX 请求通常会包含一个 'page' 参数，指示应该加载哪一页的内容。
            # 如果用户已经滚动到了最后一页，并且继续滚动，那么 'page' 参数可能会超出页面的范围。在这种情况下，如果服务器端返回一个错误响应（如 404 Not Found 或 400 Bad
            # Request），可能会导致客户端的 JavaScript 代码抛出一个错误，或者在用户界面上显示一个错误消息。
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)
    ctx = {'section': 'images', 'images': images}
    if request.is_ajax():
        return render(request, 'images/image/list_ajax.html', ctx)
    else:
        return render(request, 'images/image/list.html', ctx)

bookmarks/images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}
    Bookmark an image
{% endblock %}

{% block content %}
    <h1>Bookmark an image</h1>
    <img src="{{ request.GET.url }}" class="image-preview" alt="Lost">
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Bookmark it!">
    </form>
{% endblock %}

bookmarks/images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}
    {{ image.title }}
{% endblock %}

{% block content %}
    <h1>{{ image.title }}</h1>
    <img src="{{ image.image.url }}" class="image-detail" alt="Lost">
    {% with total_likes=image.users_like.count users_like=image.users_like.all %}
        <div class="image-info">
            <div>
                    <span class="count">
                        <span class="total">{{ total_likes }} like{{ total_likes|pluralize }}</span>
                    </span>
                <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like"
                   class="like button">
                    {% if request.user not in users_like %}
                        Like
                    {% else %}
                        Unlike
                    {% endif %}
                </a>
            </div>
            {{ image.description|linebreaks }}
        </div>
        <div class="image-likes">
            {% for user in users_like %}
                <div>
                    <img src="{{ user.profile.photo.url }}" alt="Lost">
                    <p>{{ user.first_name }}</p>
                </div>
            {% empty %}
                Nobody likes this image yet
            {% endfor %}
        </div>
    {% endwith %}
{% endblock %}

{% block domready %}
$('a.like').click(function handleLike(e) {
    e.preventDefault();
    // 在 AJAX 的回调函数中，this 不再指向触发事件的元素。因此，你需要在 AJAX 请求之前保存 this 的引用，然后在回调函数中使用这个引用
    let $this = $(this);  // save reference to this

    $this.off('click');  // Disable the link to prevent multiple concurrent req

    $.post('{% url "images:like" %}', {
        id: $(this).data('id'),  // pk of image
        action: $(this).data('action') // like or unlike
    }, function (data) { // ajax的回调函数
        if (data["status"] === "ok") {
            console.log('aaaa')
            let pre_action = $this.data('action');
            console.log('pre_action:' + pre_action)

            // toggle data-action
            $this.data('action', pre_action === 'like' ? 'unlike' : 'like');
            console.log('cur_action:' + $this.data('action'))
            // toggle link text
            $this.text(pre_action === 'like' ? 'Unlike' : 'Like');
            // update total likes
            let pre_likes = parseInt($('span.count .total').text());
            console.log('pre_likes:' + pre_likes)
            let cur_likes = pre_action === 'like' ? pre_likes + 1 : pre_likes - 1
            $('span.count .total').text(cur_likes > 1 ? cur_likes + ' likes' : cur_likes + ' like');
            console.log('cur_likes:' + $('span.count .total').text());

            // update users_like
            let this_image_likes = $('.image-likes');
            this_image_likes.empty();
            if (data["users_like"].length === 0) {
                this_image_likes.append('<p>Nobody likes this image yes</p>');
            }else{
                data["users_like"].forEach(function (user) {
                    this_image_likes.append(
                        '<div><img src="' + user.url + '" alt="Lost"><p>' + user.first_name + '</p></div>'
                    )
                });
            }
        }
    }).always(function () {
        // 在 AJAX 请求的 .always() 回调中（无论请求成功还是失败，这个回调都会被执行），我们使用 .on() 方法重新启用了链接的点击事件
        $this.on('click', handleLike);
    })
})
{% endblock %}

bookmarks/images/templates/images/image/list.html
{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock %}

{% block content %}
    <h1>Images bookmarked</h1>
    <div id="image-list">
        {% include "images/image/list_ajax.html" %}
    </div>
{% endblock %}

{% block domready %}
let page = 1;
let empty_page = false;
let block_request = false;

$(window).scroll(function () {
    let margin = $(document).height() - $(window).height() - 200;
    let scrollTop = $(this).scrollTop();
    let scrollHeight = $(document).height();
    let windowHeight = $(this).height();
    console.log(scrollTop)
    console.log(scrollHeight)
    console.log(windowHeight)

    if (scrollTop + windowHeight >= scrollHeight && empty_page === false && block_request === false){
        block_request = true;
        page += 1;
        $.get('?page=' + page, function (data) {
            if(data===''){
                empty_page = true
            }else{
                block_request = false;
                $('#image-list').append(data);
            }
        })
    }
})
{% endblock %}

bookmarks/images/templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image 300x300 crop="smart" as im %}
            <a href="{{ image.get_absolute_url }}">
                <img src="{{ im.url }}" alt="Lost">
            </a>
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">
                {{ image.title }}
            </a>
        </div>
    </div>
{% endfor %}